### ISSUE TITLE
Password generator using quantum random numbers

### ISSUE THREAD

**Issue by papermache** [ozanerhansha/qRNG#4]
Can this be turned into a password generator using random numbers from Qiskit?

**Comment by ozanerhansha** [comment]
There's no reason it couldn't. If we were to use UTF-8 for the password's characters, for example, you'd simply have to generate an 8 bit integer for every character you want in the password and just cast that collection of integers to characters. Of course, you'd have to redo invalid characters like whitespace. If you wanted variable length passwords it would be as simple as generating a random integer to see how many characters to use.

That said, depending on the password size, this might not be the most practical solution for password generation because calling one of IBM's quantum computers can take a while.
